// Wonder Kids Math Problem Solving Workbook - P.2
// Bilingual Edition (Thai–English)
// Over 198 carefully designed word problems

export const questions = [
  // ===== เรื่อง โจทย์ปัญหาการบวก (Addition Problems) =====
  {
    id: 1,
    topic: "การบวก",
    topicEN: "Addition",
    th: "แก้วมีลูกอม 25 เม็ด แม่ให้อีก 34 เม็ด แก้วมีลูกอมทั้งหมดกี่เม็ด",
    en: "Kaew has 25 candies. Her mother gives her 34 more candies. How many candies does Kaew have in total?",
  },
  {
    id: 2,
    topic: "การบวก",
    topicEN: "Addition",
    th: "บอลมีดินสอ 18 แท่ง ครูให้อีก 27 แท่ง บอลมีดินสอทั้งหมดกี่แท่ง",
    en: "Ball has 18 pencils. His teacher gives him 27 more pencils. How many pencils does Ball have in total?",
  },
  {
    id: 3,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านขนมทำขนมชิ้นเล็ก 45 ชิ้น และทำขนมชิ้นใหญ่ 32 ชิ้น ร้านทำขนมทั้งหมดกี่ชิ้น",
    en: "A snack shop makes 45 small snacks and 32 big snacks. How many snacks does the shop make in total?",
  },
  {
    id: 4,
    topic: "การบวก",
    topicEN: "Addition",
    th: "นิดเก็บเปลือกหอยได้ 36 อัน วันถัดมาเก็บได้อีก 24 อัน นิดเก็บเปลือกหอยได้ทั้งหมดกี่อัน",
    en: "Nid collects 36 shells. The next day, she collects 24 more shells. How many shells does Nid collect in total?",
  },
  {
    id: 5,
    topic: "การบวก",
    topicEN: "Addition",
    th: "สวนผลไม้มีมะม่วง 58 ลูก และมีส้ม 21 ลูก สวนผลไม้มีผลไม้ทั้งหมดกี่ลูก",
    en: "A fruit garden has 58 mangoes and 21 oranges. How many fruits are there in total?",
  },
  {
    id: 6,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ห้องสมุดมีหนังสือนิทาน 64 เล่ม และมีหนังสือการ์ตูน 29 เล่ม ห้องสมุดมีหนังสือทั้งหมดกี่เล่ม",
    en: "The library has 64 storybooks and 29 comic books. How many books are there in the library in total?",
  },
  {
    id: 7,
    topic: "การบวก",
    topicEN: "Addition",
    th: "พ่อซื้อขนมปัง 17 ชิ้น และซื้อนม 23 กล่อง พ่อซื้อของทั้งหมดกี่ชิ้น",
    en: "Father buys 17 pieces of bread and 23 cartons of milk. How many items does he buy in total?",
  },
  {
    id: 8,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ฟ้ามีดอกไม้ 42 ดอก เพื่อนให้อีก 16 ดอก ฟ้ามีดอกไม้ทั้งหมดกี่ดอก",
    en: "Fah has 42 flowers. Her friend gives her 16 more flowers. How many flowers does Fah have in total?",
  },
  {
    id: 9,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ฟาร์มเลี้ยงไก่ 75 ตัว และเลี้ยงเป็ด 14 ตัว ฟาร์มเลี้ยงสัตว์ทั้งหมดกี่ตัว",
    en: "A farm has 75 chickens and 14 ducks. How many animals are there on the farm in total?",
  },
  {
    id: 10,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ครูเตรียมสมุดแจกนักเรียน 28 เล่ม และเตรียมดินสออีก 35 แท่ง ครูเตรียมของทั้งหมดกี่ชิ้น",
    en: "The teacher prepares 28 notebooks and 35 pencils for the students. How many items does the teacher prepare in total?",
  },
  {
    id: 11,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านขายผลไม้มีแอปเปิล 39 ลูก และมีองุ่น 46 ลูก ร้านมีผลไม้ทั้งหมดกี่ลูก",
    en: "A fruit shop has 39 apples and 46 grapes. How many fruits are there in the shop in total?",
  },
  {
    id: 12,
    topic: "การบวก",
    topicEN: "Addition",
    th: "เด็กชายต้นมีลูกแก้ว 54 ลูก เด็กหญิงตาลให้อีก 25 ลูก ต้นมีลูกแก้วทั้งหมดกี่ลูก",
    en: "Ton has 54 marbles. Tan gives him 25 more marbles. How many marbles does Ton have in total?",
  },
  {
    id: 13,
    topic: "การบวก",
    topicEN: "Addition",
    th: "แม่ปลูกผักคะน้า 32 ต้น และปลูกผักบุ้ง 41 ต้น แม่ปลูกผักทั้งหมดกี่ต้น",
    en: "Mother plants 32 kale plants and 41 morning glory plants. How many plants does she plant in total?",
  },
  {
    id: 14,
    topic: "การบวก",
    topicEN: "Addition",
    th: "กล่องหนึ่งมีดินสอสี 48 แท่ง อีกกล่องมี 19 แท่ง มีกี่แท่งทั้งหมด",
    en: "One box has 48 colored pencils, and another box has 19 colored pencils. How many colored pencils are there in total?",
  },
  {
    id: 15,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านเครื่องเขียนขายสมุดได้ 63 เล่ม และขายปากกาได้ 27 ด้าม ร้านขายของได้ทั้งหมดกี่ชิ้น",
    en: "A stationery shop sells 63 notebooks and 27 pens. How many items does the shop sell in total?",
  },
  {
    id: 16,
    topic: "การบวก",
    topicEN: "Addition",
    th: "สวนสัตว์มีลิง 36 ตัว และมีนก 44 ตัว สวนสัตว์มีสัตว์ทั้งหมดกี่ตัว",
    en: "The zoo has 36 monkeys and 44 birds. How many animals are there in the zoo in total?",
  },
  {
    id: 17,
    topic: "การบวก",
    topicEN: "Addition",
    th: "มายด์มีขนม 22 ชิ้น พี่ให้อีก 58 ชิ้น มายด์มีขนมทั้งหมดกี่ชิ้น",
    en: "Mind has 22 snacks. Her older sibling gives her 58 more snacks. How many snacks does Mind have in total?",
  },
  {
    id: 18,
    topic: "การบวก",
    topicEN: "Addition",
    th: "รถบรรทุกคันหนึ่งขนกล่อง 47 กล่อง อีกคันขน 26 กล่อง รถบรรทุกขนกล่องทั้งหมดกี่กล่อง",
    en: "One truck carries 47 boxes, and another truck carries 26 boxes. How many boxes are there in total?",
  },
  {
    id: 19,
    topic: "การบวก",
    topicEN: "Addition",
    th: "โรงเรียนมีนักเรียนชาย 125 คน และนักเรียนหญิง 134 คน โรงเรียนมีนักเรียนทั้งหมดกี่คน",
    en: "A school has 125 boys and 134 girls. How many students are there in the school in total?",
  },
  {
    id: 20,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านไอศกรีมขายไอศกรีมตอนเช้า 38 ถ้วย และตอนบ่าย 47 ถ้วย ร้านขายไอศกรีมได้ทั้งหมดกี่ถ้วย",
    en: "An ice cream shop sells 38 cups in the morning and 47 cups in the afternoon. How many cups of ice cream does the shop sell in total?",
  },
  {
    id: 21,
    topic: "การบวก",
    topicEN: "Addition",
    th: "น้องปันมีสติกเกอร์ 29 แผ่น แม่ให้อีก 61 แผ่น น้องปันมีสติกเกอร์ทั้งหมดกี่แผ่น",
    en: "Pan has 29 stickers. His mother gives him 61 more stickers. How many stickers does Pan have in total?",
  },
  {
    id: 22,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ต้นไม้แถวบ้านมีนกเกาะ 34 ตัว ต่อมามาเพิ่มอีก 28 ตัว มีนกเกาะทั้งหมดกี่ตัว",
    en: "There are 34 birds on the trees near the house. Later, 28 more birds come. How many birds are there in total?",
  },
  {
    id: 23,
    topic: "การบวก",
    topicEN: "Addition",
    th: "กล่องของขวัญใบหนึ่งมีลูกบอล 55 ลูก ใบที่สองมี 44 ลูก มีลูกบอลทั้งหมดกี่ลูก",
    en: "One gift box has 55 balls, and the second box has 44 balls. How many balls are there in total?",
  },
  {
    id: 24,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านขายของเล่นมีรถของเล่น 62 คัน และมีตุ๊กตา 37 ตัว ร้านมีของเล่นทั้งหมดกี่ชิ้น",
    en: "A toy shop has 62 toy cars and 37 dolls. How many toys are there in total?",
  },
  {
    id: 25,
    topic: "การบวก",
    topicEN: "Addition",
    th: "แม่ซื้อไข่ไก่ 48 ฟอง และซื้อไข่เป็ด 26 ฟอง แม่ซื้อไข่ทั้งหมดกี่ฟอง",
    en: "Mother buys 48 chicken eggs and 26 duck eggs. How many eggs does she buy in total?",
  },
  {
    id: 26,
    topic: "การบวก",
    topicEN: "Addition",
    th: "เด็ก ๆ เก็บขวดน้ำได้ 73 ขวด ตอนบ่ายเก็บได้อีก 19 ขวด เด็ก ๆ เก็บขวดน้ำได้ทั้งหมดกี่ขวด",
    en: "The children collect 73 bottles. In the afternoon, they collect 19 more bottles. How many bottles do they collect in total?",
  },
  {
    id: 27,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ป้าแดงทำขนม 45 ชิ้น ตอนเย็นทำเพิ่มอีก 35 ชิ้น ป้าแดงทำขนมทั้งหมดกี่ชิ้น",
    en: "Aunt Daeng makes 45 snacks. In the evening, she makes 35 more snacks. How many snacks does Aunt Daeng make in total?",
  },
  {
    id: 28,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ถาดหนึ่งมีส้ม 57 ลูก อีกถาดมี 18 ลูก มีส้มทั้งหมดกี่ลูก",
    en: "One tray has 57 oranges, and another tray has 18 oranges. How many oranges are there in total?",
  },
  {
    id: 29,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ห้องเรียนมีเก้าอี้ 32 ตัว และมีโต๊ะ 28 ตัว ห้องเรียนมีเฟอร์นิเจอร์ทั้งหมดกี่ชิ้น",
    en: "A classroom has 32 chairs and 28 tables. How many pieces of furniture are there in total?",
  },
  {
    id: 30,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ฟาร์มปลามีปลานิล 84 ตัว และปลาดุก 15 ตัว ฟาร์มปลามีปลาทั้งหมดกี่ตัว",
    en: "A fish farm has 84 tilapia and 15 catfish. How many fish are there in total?",
  },
  {
    id: 31,
    topic: "การบวก",
    topicEN: "Addition",
    th: "น้องฝนวาดรูปได้ 27 รูป ครูให้อีก 43 รูป น้องฝนวาดรูปทั้งหมดกี่รูป",
    en: "Fon draws 27 pictures. The teacher gives her 43 more pictures. How many pictures does Fon have in total?",
  },
  {
    id: 32,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านขนมขายคุกกี้ได้ 56 ชิ้น และขายเค้กได้ 24 ชิ้น ร้านขายขนมได้ทั้งหมดกี่ชิ้น",
    en: "A snack shop sells 56 cookies and 24 cakes. How many snacks does the shop sell in total?",
  },
  {
    id: 33,
    topic: "การบวก",
    topicEN: "Addition",
    th: "สวนดอกไม้มีดอกกุหลาบ 68 ดอก และดอกทิวลิป 21 ดอก สวนมีดอกไม้ทั้งหมดกี่ดอก",
    en: "A flower garden has 68 roses and 21 tulips. How many flowers are there in total?",
  },
  {
    id: 34,
    topic: "การบวก",
    topicEN: "Addition",
    th: "รถบัสรับนักเรียนตอนเช้า 45 คน และรับเพิ่มอีก 39 คน รถบัสรับนักเรียนทั้งหมดกี่คน",
    en: "A bus carries 45 students in the morning and picks up 39 more students. How many students are on the bus in total?",
  },
  // Addition bonus slide 19 (topic header says การลบ but content is addition)
  {
    id: 35,
    topic: "การบวก",
    topicEN: "Addition",
    th: "บ้านหลังหนึ่งมีหน้าต่าง 14 บาน และมีประตู 6 บาน บ้านหลังนี้มีช่องเปิดทั้งหมดกี่บาน",
    en: "A house has 14 windows and 6 doors. How many openings are there in total?",
  },
  {
    id: 36,
    topic: "การบวก",
    topicEN: "Addition",
    th: "ร้านขายน้ำมีน้ำส้ม 52 ขวด และน้ำองุ่น 38 ขวด ร้านมีน้ำทั้งหมดกี่ขวด",
    en: "A drink shop has 52 bottles of orange juice and 38 bottles of grape juice. How many bottles are there in total?",
  },
  {
    id: 37,
    topic: "การบวก",
    topicEN: "Addition",
    th: "เด็กหญิงออมมีเหรียญ 67 เหรียญ พ่อให้อีก 23 เหรียญ ออมมีเหรียญทั้งหมดกี่เหรียญ",
    en: "Aom has 67 coins. Her father gives her 23 more coins. How many coins does Aom have in total?",
  },
  {
    id: 38,
    topic: "การบวก",
    topicEN: "Addition",
    th: "สนามเด็กเล่นมีลูกบอล 48 ลูก และมีห่วง 27 อัน สนามเด็กเล่นมีอุปกรณ์ทั้งหมดกี่ชิ้น",
    en: "A playground has 48 balls and 27 hoops. How many pieces of equipment are there in total?",
  },
  {
    id: 39,
    topic: "การบวก",
    topicEN: "Addition",
    th: "กล่องหนึ่งมีชอล์ก 36 แท่ง อีกกล่องมี 54 แท่ง มีชอล์กทั้งหมดกี่แท่ง",
    en: "One box has 36 pieces of chalk, and another box has 54 pieces of chalk. How many pieces of chalk are there in total?",
  },
  {
    id: 40,
    topic: "การบวก",
    topicEN: "Addition",
    th: "โรงอาหารทำข้าวกล่อง 95 กล่อง และทำเพิ่มอีก 28 กล่อง โรงอาหารทำข้าวกล่องทั้งหมดกี่กล่อง",
    en: "The school canteen prepares 95 lunch boxes and makes 28 more lunch boxes. How many lunch boxes does the canteen prepare in total?",
  },

  // ===== เรื่อง โจทย์ปัญหาการลบ (Subtraction Problems) =====
  {
    id: 41,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "แก้วมีลูกอม 78 เม็ด แจกให้เพื่อน 35 เม็ด แก้วเหลือลูกอมกี่เม็ด",
    en: "Kaew has 78 candies. She gives 35 candies to her friends. How many candies does Kaew have left?",
  },
  {
    id: 42,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "บอลมีดินสอ 64 แท่ง ทำหายไป 18 แท่ง บอลเหลือดินสอกี่แท่ง",
    en: "Ball has 64 pencils. He loses 18 pencils. How many pencils does Ball have left?",
  },
  {
    id: 43,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ร้านขนมทำคุกกี้ 95 ชิ้น ขายไป 47 ชิ้น ร้านเหลือคุกกี้กี่ชิ้น",
    en: "A snack shop makes 95 cookies. It sells 47 cookies. How many cookies are left?",
  },
  {
    id: 44,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "นิดเก็บเปลือกหอยได้ 86 อัน ให้เพื่อนไป 29 อัน นิดเหลือเปลือกหอยกี่อัน",
    en: "Nid collects 86 shells. She gives 29 shells to her friend. How many shells does Nid have left?",
  },
  {
    id: 45,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "สวนผลไม้มีส้ม 120 ลูก เก็บไปขาย 45 ลูก สวนผลไม้เหลือส้มกี่ลูก",
    en: "A fruit garden has 120 oranges. It sells 45 oranges. How many oranges are left?",
  },
  {
    id: 46,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ห้องสมุดมีหนังสือนิทาน 150 เล่ม ยืมออกไป 38 เล่ม ห้องสมุดเหลือหนังสือนิทานกี่เล่ม",
    en: "The library has 150 storybooks. 38 storybooks are borrowed. How many storybooks are left?",
  },
  {
    id: 47,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "โรงเรียนมีนักเรียน 240 คน ขาดเรียน 27 คน วันนี้มีนักเรียนมาเรียนกี่คน",
    en: "A school has 240 students. 27 students are absent. How many students come to school today?",
  },
  {
    id: 48,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ร้านไอศกรีมทำไอศกรีม 80 ถ้วย ขายไป 52 ถ้วย ร้านเหลือไอศกรีมกี่ถ้วย",
    en: "An ice cream shop makes 80 cups of ice cream. It sells 52 cups. How many cups are left?",
  },
  {
    id: 49,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "น้องปันมีสติกเกอร์ 93 แผ่น ติดไปแล้ว 46 แผ่น น้องปันเหลือสติกเกอร์กี่แผ่น",
    en: "Pan has 93 stickers. He uses 46 stickers. How many stickers does Pan have left?",
  },
  {
    id: 50,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ต้นมีลูกแก้ว 70 ลูก ให้เพื่อนไป 28 ลูก ต้นเหลือลูกแก้วกี่ลูก",
    en: "Ton has 70 marbles. He gives 28 marbles to his friend. How many marbles does Ton have left?",
  },
  {
    id: 51,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "แม่ซื้อไข่ไก่ 60 ฟอง ทำอาหารไป 17 ฟอง แม่เหลือไข่ไก่กี่ฟอง",
    en: "Mother buys 60 chicken eggs. She uses 17 eggs for cooking. How many eggs are left?",
  },
  {
    id: 52,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ร้านของเล่นมีรถของเล่น 85 คัน ขายไป 39 คัน ร้านเหลือรถของเล่นกี่คัน",
    en: "A toy shop has 85 toy cars. It sells 39 toy cars. How many toy cars are left?",
  },
  {
    id: 53,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "สวนสัตว์มีนก 96 ตัว บินหนีไป 24 ตัว สวนสัตว์เหลือนกกี่ตัว",
    en: "The zoo has 96 birds. 24 birds fly away. How many birds are left?",
  },
  {
    id: 54,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "กล่องหนึ่งมีดินสอสี 72 แท่ง แจกให้เด็ก ๆ 30 แท่ง เหลือดินสอสีในกล่องกี่แท่ง",
    en: "A box has 72 colored pencils. 30 pencils are given to the children. How many colored pencils are left in the box?",
  },
  {
    id: 55,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "โรงอาหารทำข้าวกล่อง 130 กล่อง แจกไป 55 กล่อง โรงอาหารเหลือข้าวกล่องกี่กล่อง",
    en: "The school canteen prepares 130 lunch boxes. It gives out 55 lunch boxes. How many lunch boxes are left?",
  },
  {
    id: 56,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ป้าทำขนม 105 ชิ้น ขายไป 68 ชิ้น ป้าเหลือขนมกี่ชิ้น",
    en: "An aunt makes 105 snacks. She sells 68 snacks. How many snacks are left?",
  },
  {
    id: 57,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ฟ้ามีดอกไม้ 84 ดอก ให้คุณครู 26 ดอก ฟ้าเหลือดอกไม้กี่ดอก",
    en: "Fah has 84 flowers. She gives 26 flowers to her teacher. How many flowers does Fah have left?",
  },
  {
    id: 58,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "รถบัสรับนักเรียนมา 75 คน ลงจากรถ 19 คน ตอนนี้บนรถมีนักเรียนกี่คน",
    en: "A bus picks up 75 students. 19 students get off the bus. How many students are on the bus now?",
  },
  {
    id: 59,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ตู้ปลามีปลา 58 ตัว ตายไป 12 ตัว ตู้ปลาเหลือปลากี่ตัว",
    en: "An aquarium has 58 fish. 12 fish die. How many fish are left?",
  },
  {
    id: 60,
    topic: "การลบ",
    topicEN: "Subtraction",
    th: "ร้านขายน้ำมีน้ำส้ม 100 ขวด ขายไป 43 ขวด ร้านเหลือน้ำส้มกี่ขวด",
    en: "A drink shop has 100 bottles of orange juice. It sells 43 bottles. How many bottles of orange juice are left?",
  },

  // ===== เรื่อง โจทย์ปัญหาการบวกลบระคน (Mixed Addition & Subtraction) =====
  {
    id: 61,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "กล่องชอล์กมีชอล์ก 90 แท่ง ใช้ไป 37 แท่ง เหลือชอล์กกี่แท่ง",
    en: "A box has 90 pieces of chalk. 37 pieces are used. How many pieces of chalk are left?",
  },
  {
    id: 62,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "เด็ก ๆ เก็บขวดน้ำได้ 120 ขวด ส่งไปรีไซเคิล 40 ขวด เด็ก ๆ เหลือขวดน้ำกี่ขวด",
    en: "The children collect 120 bottles. They send 40 bottles for recycling. How many bottles are left?",
  },
  {
    id: 63,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "น้องออมมีเหรียญ 95 เหรียญ ซื้อขนมไป 28 เหรียญ น้องออมเหลือเหรียญกี่เหรียญ",
    en: "Aom has 95 coins. She spends 28 coins on snacks. How many coins does Aom have left?",
  },
  {
    id: 64,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "ร้านเครื่องเขียนมีสมุด 88 เล่ม ขายไป 35 เล่ม ร้านเหลือสมุดกี่เล่ม",
    en: "A stationery shop has 88 notebooks. It sells 35 notebooks. How many notebooks are left?",
  },
  {
    id: 65,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "สวนดอกไม้มีดอกกุหลาบ 140 ดอก ตัดไปขาย 67 ดอก เหลือดอกกุหลาบกี่ดอก",
    en: "A flower garden has 140 roses. 67 roses are cut and sold. How many roses are left?",
  },
  {
    id: 66,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "สนามเด็กเล่นมีลูกบอล 60 ลูก เด็ก ๆ เอาไปเล่น 22 ลูก สนามเหลือลูกบอลกี่ลูก",
    en: "A playground has 60 balls. The children take 22 balls to play. How many balls are left?",
  },
  {
    id: 67,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "โรงเรียนมีโต๊ะ 75 ตัว ชำรุด 8 ตัว ใช้ได้กี่ตัว",
    en: "A school has 75 tables. 8 tables are broken. How many tables can still be used?",
  },
  {
    id: 68,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "บ้านหลังหนึ่งมีหน้าต่าง 20 บาน ซ่อมปิดไป 6 บาน ตอนนี้มีหน้าต่างที่ใช้งานได้กี่บาน",
    en: "A house has 20 windows. 6 windows are closed for repair. How many windows can be used now?",
  },
  {
    id: 69,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "ลุงมีมะม่วง 96 ลูก แจกให้เพื่อนบ้าน 45 ลูก ลุงเหลือมะม่วงกี่ลูก",
    en: "An uncle has 96 mangoes. He gives 45 mangoes to his neighbors. How many mangoes does he have left?",
  },
  {
    id: 70,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "ถุงขนมมีขนม 110 ชิ้น เด็ก ๆ กินไป 74 ชิ้น เหลือขนมกี่ชิ้น",
    en: "A bag has 110 snacks. The children eat 74 snacks. How many snacks are left?",
  },
  {
    id: 71,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "ร้านหนังสือมีหนังสือการ์ตูน 150 เล่ม ขายไป 58 เล่ม ร้านเหลือหนังสือการ์ตูนกี่เล่ม",
    en: "A bookstore has 150 comic books. It sells 58 comic books. How many comic books are left?",
  },
  {
    id: 72,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "ฟาร์มมีเป็ด 83 ตัว ขายไป 29 ตัว ฟาร์มเหลือเป็ดกี่ตัว",
    en: "A farm has 83 ducks. It sells 29 ducks. How many ducks are left?",
  },
  {
    id: 73,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "ต้นไม้มีนกเกาะ 65 ตัว บินไป 17 ตัว เหลือนกเกาะกี่ตัว",
    en: "There are 65 birds on a tree. 17 birds fly away. How many birds are left?",
  },
  {
    id: 74,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "แม่มีเงิน 200 บาท ซื้อขนม 65 บาท แม่เหลือเงินกี่บาท",
    en: "Mother has 200 baht. She spends 65 baht on snacks. How many baht does she have left?",
  },
  {
    id: 75,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "เด็กหญิงตาลมีดินสอ 50 แท่ง ให้เพื่อนไป 13 แท่ง ตาลเหลือดินสอกี่แท่ง",
    en: "Tan has 50 pencils. She gives 13 pencils to her friend. How many pencils does Tan have left?",
  },
  {
    id: 76,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "รถบรรทุกมีกล่อง 140 กล่อง ส่งของไปแล้ว 55 กล่อง รถบรรทุกเหลือกล่องกี่กล่อง",
    en: "A truck has 140 boxes. 55 boxes are delivered. How many boxes are left on the truck?",
  },
  {
    id: 77,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "โรงงานทำของเล่น 300 ชิ้น ส่งไปขาย 125 ชิ้น โรงงานเหลือของเล่นกี่ชิ้น",
    en: "A factory makes 300 toys. It sends 125 toys to sell. How many toys are left?",
  },
  {
    id: 78,
    topic: "การบวกลบระคน",
    topicEN: "Mixed Addition & Subtraction",
    th: "กล่องผลไม้มีแอปเปิล 90 ลูก หยิบไปทำสลัด 34 ลูก เหลือแอปเปิลกี่ลูก",
    en: "A fruit box has 90 apples. 34 apples are used to make salad. How many apples are left?",
  },

  // ===== เรื่อง โจทย์ปัญหาการบวกลบระคน 3-step (3-Step Mixed) =====
  {
    id: 79,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "แม่มีไข่ไก่ 85 ฟอง ซื้อเพิ่มอีก 40 ฟอง แล้วใช้ทำขนมไป 36 ฟอง แม่เหลือไข่ไก่กี่ฟอง",
    en: "Mother has 85 chicken eggs. She buys 40 more eggs and then uses 36 eggs for baking. How many eggs does she have left?",
  },
  {
    id: 80,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านขนมทำคุกกี้ 120 ชิ้น ขายไป 45 ชิ้น แล้วทำเพิ่มอีก 30 ชิ้น ตอนนี้ร้านมีคุกกี้กี่ชิ้น",
    en: "A snack shop makes 120 cookies. It sells 45 cookies and then makes 30 more cookies. How many cookies does the shop have now?",
  },
  {
    id: 81,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "น้องออมมีสติกเกอร์ 70 แผ่น ได้เพิ่มจากเพื่อน 25 แผ่น แล้วติดไป 38 แผ่น น้องออมเหลือสติกเกอร์กี่แผ่น",
    en: "Aom has 70 stickers. She gets 25 more stickers from a friend and then uses 38 stickers. How many stickers does Aom have left?",
  },
  {
    id: 82,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ฟาร์มมีเป็ด 95 ตัว ขายไป 27 ตัว แล้วซื้อมาเพิ่มอีก 18 ตัว ฟาร์มมีเป็ดทั้งหมดกี่ตัว",
    en: "A farm has 95 ducks. It sells 27 ducks and then buys 18 more ducks. How many ducks are there on the farm now?",
  },
  {
    id: 83,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "โรงอาหารทำข้าวกล่อง 150 กล่อง แจกไป 60 กล่อง แล้วทำเพิ่มอีก 35 กล่อง โรงอาหารมีข้าวกล่องกี่กล่อง",
    en: "The school canteen prepares 150 lunch boxes. It gives out 60 lunch boxes and then makes 35 more lunch boxes. How many lunch boxes does the canteen have now?",
  },
  {
    id: 84,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ต้นมีลูกแก้ว 64 ลูก ทำหายไป 19 ลูก แล้วคุณพ่อให้อีก 28 ลูก ต้นมีลูกแก้วกี่ลูก",
    en: "Ton has 64 marbles. He loses 19 marbles, and then his father gives him 28 more marbles. How many marbles does Ton have now?",
  },
  {
    id: 85,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านขายน้ำมีน้ำส้ม 110 ขวด ขายไป 48 ขวด แล้วรับของมาเพิ่มอีก 25 ขวด ร้านมีน้ำส้มกี่ขวด",
    en: "A drink shop has 110 bottles of orange juice. It sells 48 bottles and then receives 25 more bottles. How many bottles of orange juice does the shop have now?",
  },
  {
    id: 86,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ห้องสมุดมีหนังสือนิทาน 180 เล่ม ยืมออกไป 55 เล่ม แล้วนำหนังสือมาเพิ่มอีก 20 เล่ม ห้องสมุดมีหนังสือนิทานกี่เล่ม",
    en: "The library has 180 storybooks. 55 books are borrowed, and then 20 more books are added. How many storybooks does the library have now?",
  },
  {
    id: 87,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "นิดเก็บเปลือกหอยได้ 90 อัน ให้เพื่อนไป 26 อัน แล้วเก็บเพิ่มอีก 15 อัน นิดมีเปลือกหอยกี่อัน",
    en: "Nid collects 90 shells. She gives 26 shells to her friend and then collects 15 more shells. How many shells does Nid have now?",
  },
  {
    id: 88,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านของเล่นมีตุ๊กตา 75 ตัว ขายไป 18 ตัว แล้วรับเพิ่มมาอีก 40 ตัว ตอนนี้ร้านมีตุ๊กตากี่ตัว",
    en: "A toy shop has 75 dolls. It sells 18 dolls and then receives 40 more dolls. How many dolls does the shop have now?",
  },
  {
    id: 89,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "แม่มีเงิน 300 บาท ได้เงินเพิ่ม 120 บาท แล้วซื้อของไป 185 บาท แม่เหลือเงินกี่บาท",
    en: "Mother has 300 baht. She gets 120 more baht and then spends 185 baht on shopping. How much money does she have left?",
  },
  {
    id: 90,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "รถบัสมีนักเรียนอยู่ 45 คน รับเพิ่มอีก 28 คน แล้วลงจากรถ 19 คน ตอนนี้บนรถมีนักเรียนกี่คน",
    en: "There are 45 students on a bus. 28 more students get on the bus, and then 19 students get off. How many students are on the bus now?",
  },
  {
    id: 91,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "สนามเด็กเล่นมีลูกบอล 60 ลูก เด็ก ๆ เอาไปเล่น 22 ลูก แล้วครูเอามาเพิ่มอีก 15 ลูก สนามมีลูกบอลกี่ลูก",
    en: "A playground has 60 balls. The children take 22 balls to play, and then the teacher adds 15 more balls. How many balls are there now?",
  },
  {
    id: 92,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "สวนผลไม้มีส้ม 140 ลูก เก็บไปขาย 35 ลูก แล้วเก็บเพิ่มจากสวนอีก 20 ลูก สวนผลไม้มีส้มกี่ลูก",
    en: "A fruit garden has 140 oranges. It sells 35 oranges and then collects 20 more oranges. How many oranges are there now?",
  },
  {
    id: 93,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ป้ามีขนม 95 ชิ้น ขายไป 40 ชิ้น แล้วทำเพิ่มอีก 18 ชิ้น ป้าเหลือขนมกี่ชิ้น",
    en: "An aunt has 95 snacks. She sells 40 snacks and then makes 18 more snacks. How many snacks does she have left?",
  },
  {
    id: 94,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ฟ้ามีดอกไม้ 80 ดอก ได้เพิ่มอีก 25 ดอก แล้วให้คุณครู 30 ดอก ฟ้าเหลือดอกไม้กี่ดอก",
    en: "Fah has 80 flowers. She gets 25 more flowers and then gives 30 flowers to her teacher. How many flowers does Fah have left?",
  },
  {
    id: 95,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านเครื่องเขียนมีสมุด 90 เล่ม ขายไป 36 เล่ม แล้วรับมาเพิ่มอีก 50 เล่ม ร้านมีสมุดกี่เล่ม",
    en: "A stationery shop has 90 notebooks. It sells 36 notebooks and then receives 50 more notebooks. How many notebooks does the shop have now?",
  },
  {
    id: 96,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "กล่องดินสอสีมี 72 แท่ง แจกให้เพื่อน 20 แท่ง แล้วซื้อเพิ่มอีก 15 แท่ง ตอนนี้มีดินสอสีทั้งหมดกี่แท่ง",
    en: "A box has 72 colored pencils. 20 pencils are given to friends, and then 15 more pencils are bought. How many colored pencils are there now?",
  },
  {
    id: 97,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ตู้ปลามีปลา 58 ตัว เพิ่มปลาใหม่อีก 17 ตัว แล้วตายไป 9 ตัว ตอนนี้ตู้ปลามีปลากี่ตัว",
    en: "An aquarium has 58 fish. 17 new fish are added, and then 9 fish die. How many fish are there now?",
  },
  {
    id: 98,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "สวนสัตว์มีนก 120 ตัว บินหนีไป 33 ตัว แล้วมีนกย้ายมาเพิ่มอีก 12 ตัว สวนสัตว์มีนกกี่ตัว",
    en: "A zoo has 120 birds. 33 birds fly away, and then 12 more birds come. How many birds are there now?",
  },
  {
    id: 99,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "โรงงานทำของเล่น 200 ชิ้น ส่งไปขาย 85 ชิ้น แล้วทำเพิ่มอีก 40 ชิ้น โรงงานเหลือของเล่นกี่ชิ้น",
    en: "A factory makes 200 toys. It sends 85 toys to sell and then makes 40 more toys. How many toys are left?",
  },
  {
    id: 100,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "แม่ซื้อนม 60 กล่อง ดื่มไป 18 กล่อง แล้วซื้อเพิ่มอีก 25 กล่อง แม่มีนมกี่กล่อง",
    en: "Mother buys 60 cartons of milk. She drinks 18 cartons and then buys 25 more cartons. How many cartons of milk does she have now?",
  },
  {
    id: 101,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ต้นไม้มีนกเกาะ 55 ตัว บินไป 14 ตัว แล้วบินมาเพิ่มอีก 9 ตัว ตอนนี้มีนกเกาะกี่ตัว",
    en: "There are 55 birds on a tree. 14 birds fly away, and then 9 more birds come. How many birds are there now?",
  },
  {
    id: 102,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านเค้กทำเค้ก 80 ชิ้น ขายไป 35 ชิ้น แล้วทำเพิ่มอีก 22 ชิ้น ตอนนี้ร้านมีเค้กกี่ชิ้น",
    en: "A cake shop makes 80 cakes. It sells 35 cakes and then makes 22 more cakes. How many cakes does the shop have now?",
  },
  {
    id: 103,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "เด็ก ๆ เก็บขวดน้ำได้ 150 ขวด ส่งไปรีไซเคิล 50 ขวด แล้วเก็บเพิ่มอีก 30 ขวด เด็ก ๆ เหลือขวดน้ำกี่ขวด",
    en: "The children collect 150 bottles. They send 50 bottles for recycling and then collect 30 more bottles. How many bottles are left?",
  },
  {
    id: 104,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "บ้านหลังหนึ่งมีหน้าต่าง 18 บาน ซ่อมปิดไป 5 บาน แล้วติดตั้งเพิ่มอีก 4 บาน ตอนนี้มีหน้าต่างใช้งานได้กี่บาน",
    en: "A house has 18 windows. 5 windows are closed for repair, and then 4 new windows are installed. How many windows can be used now?",
  },
  {
    id: 105,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ห้องเรียนมีนักเรียน 32 คน เช้ามามาเพิ่มอีก 6 คน แล้วกลับบ้านก่อน 4 คน ห้องเรียนมีนักเรียนกี่คน",
    en: "A classroom has 32 students. 6 more students arrive in the morning, and then 4 students go home early. How many students are in the classroom now?",
  },
  {
    id: 106,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านผลไม้มีแอปเปิล 95 ลูก ขายไป 28 ลูก แล้วรับมาเพิ่มอีก 40 ลูก ร้านมีแอปเปิลกี่ลูก",
    en: "A fruit shop has 95 apples. It sells 28 apples and then receives 40 more apples. How many apples does the shop have now?",
  },
  {
    id: 107,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ฟาร์มมีไก่ 130 ตัว ขายไป 45 ตัว แล้วซื้อมาเพิ่มอีก 20 ตัว ฟาร์มมีไก่กี่ตัว",
    en: "A farm has 130 chickens. It sells 45 chickens and then buys 20 more chickens. How many chickens are there now?",
  },
  {
    id: 108,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "กล่องชอล์กมีชอล์ก 100 แท่ง ใช้ไป 37 แท่ง แล้วซื้อเพิ่มอีก 25 แท่ง ตอนนี้มีชอล์กกี่แท่ง",
    en: "A box has 100 pieces of chalk. 37 pieces are used, and then 25 more pieces are bought. How many pieces of chalk are there now?",
  },
  {
    id: 109,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "น้องปันมีเงิน 250 บาท ได้เพิ่มอีก 80 บาท แล้วซื้อขนมไป 95 บาท น้องปันเหลือเงินกี่บาท",
    en: "Pan has 250 baht. He gets 80 more baht and then spends 95 baht on snacks. How much money does Pan have left?",
  },
  {
    id: 110,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านไอศกรีมทำไอศกรีม 90 ถ้วย ขายไป 52 ถ้วย แล้วทำเพิ่มอีก 30 ถ้วย ร้านมีไอศกรีมกี่ถ้วย",
    en: "An ice cream shop makes 90 cups of ice cream. It sells 52 cups and then makes 30 more cups. How many cups of ice cream does the shop have now?",
  },
  {
    id: 111,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "สวนดอกไม้มีดอกกุหลาบ 160 ดอก ตัดไปขาย 70 ดอก แล้วมีดอกใหม่บานเพิ่มอีก 25 ดอก เหลือดอกกุหลาบกี่ดอก",
    en: "A flower garden has 160 roses. 70 roses are cut and sold, and then 25 new roses bloom. How many roses are left?",
  },
  {
    id: 112,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านหนังสือมีหนังสือการ์ตูน 140 เล่ม ขายไป 50 เล่ม แล้วรับเพิ่มอีก 35 เล่ม ร้านมีหนังสือการ์ตูนกี่เล่ม",
    en: "A bookstore has 140 comic books. It sells 50 comic books and then receives 35 more comic books. How many comic books does the shop have now?",
  },
  {
    id: 113,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ฟาร์มปลามีปลานิล 110 ตัว ตายไป 12 ตัว แล้วซื้อมาเพิ่มอีก 18 ตัว ฟาร์มปลามีปลากี่ตัว",
    en: "A fish farm has 110 tilapia. 12 fish die, and then 18 more fish are added. How many fish are there now?",
  },
  {
    id: 114,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "โรงเรียนมีเก้าอี้ 120 ตัว ย้ายไปห้องอื่น 35 ตัว แล้วซื้อเพิ่มอีก 20 ตัว โรงเรียนมีเก้าอี้กี่ตัว",
    en: "A school has 120 chairs. 35 chairs are moved to another room, and then 20 more chairs are bought. How many chairs are there now?",
  },
  {
    id: 115,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "แม่ทำแซนด์วิช 65 ชิ้น แจกให้เด็ก ๆ 28 ชิ้น แล้วทำเพิ่มอีก 19 ชิ้น แม่มีแซนด์วิชกี่ชิ้น",
    en: "Mother makes 65 sandwiches. She gives 28 sandwiches to the children and then makes 19 more sandwiches. How many sandwiches does she have now?",
  },
  {
    id: 116,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "ร้านของเล่นมีรถของเล่น 90 คัน ขายไป 27 คัน แล้วรับมาเพิ่มอีก 15 คัน ร้านมีรถของเล่นกี่คัน",
    en: "A toy shop has 90 toy cars. It sells 27 toy cars and then receives 15 more toy cars. How many toy cars does the shop have now?",
  },
  {
    id: 117,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "แม่มีไข่ 140 ฟอง ใช้ไป 55 ฟอง แล้วซื้อเพิ่มอีก 30 ฟอง แม่เหลือไข่กี่ฟอง",
    en: "Mother has 140 eggs. She uses 55 eggs and then buys 30 more eggs. How many eggs does she have left?",
  },
  {
    id: 118,
    topic: "การบวกลบระคน (3 ขั้นตอน)",
    topicEN: "3-Step Mixed Addition & Subtraction",
    th: "โรงอาหารมีถาดอาหาร 85 ใบ แจกไป 32 ใบ แล้วรับมาเพิ่มอีก 20 ใบ โรงอาหารมีถาดอาหารกี่ใบ",
    en: "The school canteen has 85 trays. It gives out 32 trays and then receives 20 more trays. How many trays does the canteen have now?",
  },

  // ===== เรื่อง โจทย์ปัญหาการคูณ (Multiplication Problems) =====
  {
    id: 119,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีถุงลูกอม 6 ถุง ถุงละ 5 เม็ด มีลูกอมทั้งหมดกี่เม็ด",
    en: "There are 6 bags of candies. Each bag has 5 candies. How many candies are there in total?",
  },
  {
    id: 120,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ครูมีสมุด 4 กอง กองละ 8 เล่ม ครูมีสมุดทั้งหมดกี่เล่ม",
    en: "The teacher has 4 stacks of notebooks. Each stack has 8 notebooks. How many notebooks does the teacher have in total?",
  },
  {
    id: 121,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "แม่ซื้อไข่ไก่ 7 แผง แผงละ 10 ฟอง แม่ซื้อไข่ไก่ทั้งหมดกี่ฟอง",
    en: "Mother buys 7 trays of eggs. Each tray has 10 eggs. How many eggs does she buy in total?",
  },
  {
    id: 122,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีจานขนม 5 ใบ ใบละ 6 ชิ้น มีขนมทั้งหมดกี่ชิ้น",
    en: "There are 5 plates of snacks. Each plate has 6 snacks. How many snacks are there in total?",
  },
  {
    id: 123,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "สวนมีต้นมะม่วง 3 แถว แถวละ 9 ต้น สวนมีต้นมะม่วงทั้งหมดกี่ต้น",
    en: "A garden has 3 rows of mango trees. Each row has 9 trees. How many mango trees are there in total?",
  },
  {
    id: 124,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีเด็ก 8 คน คนละ 2 ดินสอ เด็กทั้งหมดมีดินสอกี่แท่ง",
    en: "There are 8 children. Each child has 2 pencils. How many pencils do the children have in total?",
  },
  {
    id: 125,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ร้านขายน้ำมีลังน้ำส้ม 9 ลัง ลังละ 12 ขวด ร้านมีน้ำส้มทั้งหมดกี่ขวด",
    en: "A drink shop has 9 crates of orange juice. Each crate has 12 bottles. How many bottles of orange juice are there in total?",
  },
  {
    id: 126,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีเก้าอี้ 6 แถว แถวละ 7 ตัว มีเก้าอี้ทั้งหมดกี่ตัว",
    en: "There are 6 rows of chairs. Each row has 7 chairs. How many chairs are there in total?",
  },
  {
    id: 127,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "แม่ทำคุกกี้ 4 กล่อง กล่องละ 9 ชิ้น แม่ทำคุกกี้ทั้งหมดกี่ชิ้น",
    en: "Mother makes 4 boxes of cookies. Each box has 9 cookies. How many cookies does she make in total?",
  },
  {
    id: 128,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ฟาร์มมีคอกไก่ 5 คอก คอกละ 8 ตัว ฟาร์มมีไก่ทั้งหมดกี่ตัว",
    en: "A farm has 5 chicken coops. Each coop has 8 chickens. How many chickens are there on the farm in total?",
  },
  {
    id: 129,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีหนังสือการ์ตูน 7 ชั้น ชั้นละ 6 เล่ม มีหนังสือการ์ตูนทั้งหมดกี่เล่ม",
    en: "There are 7 shelves of comic books. Each shelf has 6 books. How many comic books are there in total?",
  },
  {
    id: 130,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีขวดน้ำ 3 แพ็ก แพ็กละ 15 ขวด มีขวดน้ำทั้งหมดกี่ขวด",
    en: "There are 3 packs of water bottles. Each pack has 15 bottles. How many bottles are there in total?",
  },
  {
    id: 131,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ครูติดสติกเกอร์ 6 แผ่น แผ่นละ 10 ดวง ครูติดสติกเกอร์ทั้งหมดกี่ดวง",
    en: "The teacher sticks 6 sheets of stickers. Each sheet has 10 stickers. How many stickers does the teacher stick in total?",
  },
  {
    id: 132,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ร้านขายผลไม้มีส้ม 8 ถุง ถุงละ 4 ลูก ร้านมีส้มทั้งหมดกี่ลูก",
    en: "A fruit shop has 8 bags of oranges. Each bag has 4 oranges. How many oranges are there in total?",
  },
  {
    id: 133,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีถุงขนม 9 ถุง ถุงละ 3 ชิ้น มีขนมทั้งหมดกี่ชิ้น",
    en: "There are 9 bags of snacks. Each bag has 3 snacks. How many snacks are there in total?",
  },
  {
    id: 134,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "นักเรียน 5 คน เก็บขวดได้คนละ 7 ขวด นักเรียนเก็บขวดได้ทั้งหมดกี่ขวด",
    en: "Five students collect 7 bottles each. How many bottles do they collect in total?",
  },
  {
    id: 135,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีตู้ปลา 4 ตู้ ตู้ละ 12 ตัว มีปลาทั้งหมดกี่ตัว",
    en: "There are 4 fish tanks. Each tank has 12 fish. How many fish are there in total?",
  },
  {
    id: 136,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีแถวลูกโป่ง 7 แถว แถวละ 5 ใบ มีลูกโป่งทั้งหมดกี่ใบ",
    en: "There are 7 rows of balloons. Each row has 5 balloons. How many balloons are there in total?",
  },
  {
    id: 137,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "แม่ซื้อดินสอสี 6 กล่อง กล่องละ 8 แท่ง แม่ซื้อดินสอสีทั้งหมดกี่แท่ง",
    en: "Mother buys 6 boxes of colored pencils. Each box has 8 pencils. How many colored pencils does she buy in total?",
  },
  {
    id: 138,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ร้านทำแซนด์วิช 9 ถาด ถาดละ 6 ชิ้น ร้านทำแซนด์วิชทั้งหมดกี่ชิ้น",
    en: "A sandwich shop makes 9 trays of sandwiches. Each tray has 6 sandwiches. How many sandwiches does the shop make in total?",
  },
  {
    id: 139,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีรถของเล่น 8 กล่อง กล่องละ 4 คัน มีรถของเล่นทั้งหมดกี่คัน",
    en: "There are 8 boxes of toy cars. Each box has 4 toy cars. How many toy cars are there in total?",
  },
  {
    id: 140,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีเด็ก 6 กลุ่ม กลุ่มละ 5 คน มีเด็กทั้งหมดกี่คน",
    en: "There are 6 groups of children. Each group has 5 children. How many children are there in total?",
  },
  {
    id: 141,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีชอล์ก 7 กล่อง กล่องละ 9 แท่ง มีชอล์กทั้งหมดกี่แท่ง",
    en: "There are 7 boxes of chalk. Each box has 9 pieces of chalk. How many pieces of chalk are there in total?",
  },
  {
    id: 142,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "สวนดอกไม้มีดอกกุหลาบ 6 แปลง แปลงละ 7 ดอก มีดอกกุหลาบทั้งหมดกี่ดอก",
    en: "A flower garden has 6 plots of roses. Each plot has 7 roses. How many roses are there in total?",
  },
  {
    id: 143,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ร้านไอศกรีมทำไอศกรีม 5 ถาด ถาดละ 12 ถ้วย ทำไอศกรีมทั้งหมดกี่ถ้วย",
    en: "An ice cream shop makes 5 trays of ice cream. Each tray has 12 cups. How many cups of ice cream are made in total?",
  },
  {
    id: 144,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีหนังสือนิทาน 3 กอง กองละ 20 เล่ม มีหนังสือนิทานทั้งหมดกี่เล่ม",
    en: "There are 3 stacks of storybooks. Each stack has 20 books. How many storybooks are there in total?",
  },
  {
    id: 145,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีผลไม้ 8 ตะกร้า ตะกร้าละ 9 ลูก มีผลไม้ทั้งหมดกี่ลูก",
    en: "There are 8 baskets of fruit. Each basket has 9 fruits. How many fruits are there in total?",
  },
  {
    id: 146,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีถุงข้าวสาร 4 ถุง ถุงละ 25 กิโลกรัม มีข้าวสารทั้งหมดกี่กิโลกรัม",
    en: "There are 4 bags of rice. Each bag weighs 25 kilograms. How many kilograms of rice are there in total?",
  },
  {
    id: 147,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ห้องเรียนมีโต๊ะ 5 แถว แถวละ 6 ตัว มีโต๊ะทั้งหมดกี่ตัว",
    en: "A classroom has 5 rows of tables. Each row has 6 tables. How many tables are there in total?",
  },
  {
    id: 148,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีดินสอ 9 กล่อง กล่องละ 10 แท่ง มีดินสอทั้งหมดกี่แท่ง",
    en: "There are 9 boxes of pencils. Each box has 10 pencils. How many pencils are there in total?",
  },
  {
    id: 149,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีขนมปัง 7 ถุง ถุงละ 8 ชิ้น มีขนมปังทั้งหมดกี่ชิ้น",
    en: "There are 7 bags of bread. Each bag has 8 pieces. How many pieces of bread are there in total?",
  },
  {
    id: 150,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีขวดนม 6 ลัง ลังละ 20 ขวด มีขวดนมทั้งหมดกี่ขวด",
    en: "There are 6 crates of milk bottles. Each crate has 20 bottles. How many bottles of milk are there in total?",
  },
  {
    id: 151,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ร้านขายของเล่นมีตุ๊กตา 4 ชั้น ชั้นละ 15 ตัว มีตุ๊กตาทั้งหมดกี่ตัว",
    en: "A toy shop has 4 shelves of dolls. Each shelf has 15 dolls. How many dolls are there in total?",
  },
  {
    id: 152,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีนักเรียน 8 แถว แถวละ 4 คน มีนักเรียนทั้งหมดกี่คน",
    en: "There are 8 rows of students. Each row has 4 students. How many students are there in total?",
  },
  {
    id: 153,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "แม่ทำขนม 9 จาน จานละ 7 ชิ้น แม่ทำขนมทั้งหมดกี่ชิ้น",
    en: "Mother makes 9 plates of snacks. Each plate has 7 snacks. How many snacks does she make in total?",
  },
  {
    id: 154,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีปลูกผัก 6 แปลง แปลงละ 9 ต้น มีต้นผักทั้งหมดกี่ต้น",
    en: "There are 6 vegetable plots. Each plot has 9 plants. How many vegetable plants are there in total?",
  },
  {
    id: 155,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "มีลูกอม 10 ถุง ถุงละ 6 เม็ด มีลูกอมทั้งหมดกี่เม็ด",
    en: "There are 10 bags of candies. Each bag has 6 candies. How many candies are there in total?",
  },
  {
    id: 156,
    topic: "การคูณ",
    topicEN: "Multiplication",
    th: "ร้านมีน้ำผลไม้ 5 แพ็ก แพ็กละ 24 กล่อง ร้านมีน้ำผลไม้ทั้งหมดกี่กล่อง",
    en: "A shop has 5 packs of fruit juice. Each pack has 24 boxes. How many boxes of fruit juice are there in total?",
  },

  // ===== เรื่อง โจทย์ปัญหาการหาร (Division Problems) =====
  {
    id: 157,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีลูกอม 30 เม็ด แบ่งให้เด็ก 5 คนเท่า ๆ กัน เด็กคนละกี่เม็ด",
    en: "There are 30 candies. They are shared equally among 5 children. How many candies does each child get?",
  },
  {
    id: 158,
    topic: "การหาร",
    topicEN: "Division",
    th: "ครูมีดินสอ 24 แท่ง แจกให้นักเรียน 6 คนเท่า ๆ กัน นักเรียนคนละกี่แท่ง",
    en: "The teacher has 24 pencils. She gives them equally to 6 students. How many pencils does each student get?",
  },
  {
    id: 159,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีส้ม 28 ลูก ใส่ถุงถุงละ 4 ลูก จะได้กี่ถุง",
    en: "There are 28 oranges. If 4 oranges are put into each bag, how many bags are there?",
  },
  {
    id: 160,
    topic: "การหาร",
    topicEN: "Division",
    th: "แม่มีไข่ไก่ 36 ฟอง ใส่แผงแผงละ 6 ฟอง จะได้กี่แผง",
    en: "Mother has 36 eggs. If each tray holds 6 eggs, how many trays are needed?",
  },
  {
    id: 161,
    topic: "การหาร",
    topicEN: "Division",
    th: "ร้านขนมมีคุกกี้ 40 ชิ้น แบ่งใส่จานจานละ 8 ชิ้น จะได้กี่จาน",
    en: "A snack shop has 40 cookies. If 8 cookies are placed on each plate, how many plates are there?",
  },
  {
    id: 162,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีน้ำผลไม้ 45 กล่อง แบ่งให้เด็ก 9 คนเท่า ๆ กัน เด็กคนละกี่กล่อง",
    en: "There are 45 juice boxes. They are shared equally among 9 children. How many boxes does each child get?",
  },
  {
    id: 163,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีลูกโป่ง 35 ใบ แบ่งใส่ถุงถุงละ 5 ใบ จะได้กี่ถุง",
    en: "There are 35 balloons. If 5 balloons are put into each bag, how many bags are there?",
  },
  {
    id: 164,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีสมุด 48 เล่ม แบ่งเป็นกองกองละ 6 เล่ม จะได้กี่กอง",
    en: "There are 48 notebooks. If each stack has 6 notebooks, how many stacks are there?",
  },
  {
    id: 165,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีขนมปัง 54 ชิ้น แบ่งให้เด็ก 9 คนเท่า ๆ กัน เด็กคนละกี่ชิ้น",
    en: "There are 54 pieces of bread. They are shared equally among 9 children. How many pieces does each child get?",
  },
  {
    id: 166,
    topic: "การหาร",
    topicEN: "Division",
    th: "สวนมีต้นกล้า 32 ต้น ปลูกเป็นแถวแถวละ 8 ต้น จะได้กี่แถว",
    en: "A garden has 32 seedlings. If 8 seedlings are planted in each row, how many rows are there?",
  },
  {
    id: 167,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีปลาทอง 27 ตัว แบ่งใส่ตู้ 3 ตู้เท่า ๆ กัน ตู้ละกี่ตัว",
    en: "There are 27 goldfish. They are divided equally into 3 tanks. How many fish are in each tank?",
  },
  {
    id: 168,
    topic: "การหาร",
    topicEN: "Division",
    th: "ร้านมีดินสอสี 56 แท่ง ใส่กล่องกล่องละ 7 แท่ง จะได้กี่กล่อง",
    en: "A shop has 56 colored pencils. If 7 pencils are put into each box, how many boxes are there?",
  },
  {
    id: 169,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีชอล์ก 63 แท่ง แบ่งให้ครู 9 คนเท่า ๆ กัน ครูคนละกี่แท่ง",
    en: "There are 63 pieces of chalk. They are shared equally among 9 teachers. How many pieces does each teacher get?",
  },
  {
    id: 170,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีสติกเกอร์ 50 แผ่น แบ่งให้เด็ก 5 คนเท่า ๆ กัน เด็กคนละกี่แผ่น",
    en: "There are 50 stickers. They are shared equally among 5 children. How many stickers does each child get?",
  },
  {
    id: 171,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีนม 72 กล่อง แบ่งใส่ลังลังละ 12 กล่อง จะได้กี่ลัง",
    en: "There are 72 cartons of milk. If each crate holds 12 cartons, how many crates are there?",
  },
  {
    id: 172,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีหนังสือการ์ตูน 45 เล่ม แบ่งใส่ชั้น 5 ชั้นเท่า ๆ กัน ชั้นละกี่เล่ม",
    en: "There are 45 comic books. They are divided equally onto 5 shelves. How many books are on each shelf?",
  },
  {
    id: 173,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีขวดน้ำ 64 ขวด แบ่งใส่กล่องกล่องละ 8 ขวด จะได้กี่กล่อง",
    en: "There are 64 bottles of water. If 8 bottles are put into each box, how many boxes are there?",
  },
  {
    id: 174,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีลูกแก้ว 36 ลูก แบ่งให้เด็ก 4 คนเท่า ๆ กัน เด็กคนละกี่ลูก",
    en: "There are 36 marbles. They are shared equally among 4 children. How many marbles does each child get?",
  },
  {
    id: 175,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีดอกไม้ 42 ดอก จัดเป็นช่อช่อละ 6 ดอก จะได้กี่ช่อ",
    en: "There are 42 flowers. If each bouquet has 6 flowers, how many bouquets are there?",
  },
  {
    id: 176,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีข้าวกล่อง 80 กล่อง แบ่งให้ห้องเรียน 10 ห้องเท่า ๆ กัน ห้องละกี่กล่อง",
    en: "There are 80 lunch boxes. They are shared equally among 10 classrooms. How many lunch boxes does each classroom get?",
  },
  {
    id: 177,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีไอศกรีม 66 ถ้วย แบ่งให้เด็ก 6 คนเท่า ๆ กัน เด็กคนละกี่ถ้วย",
    en: "There are 66 cups of ice cream. They are shared equally among 6 children. How many cups does each child get?",
  },
  {
    id: 178,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีส้ม 90 ลูก แบ่งใส่ตะกร้า 9 ใบเท่า ๆ กัน ตะกร้าละกี่ลูก",
    en: "There are 90 oranges. They are divided equally into 9 baskets. How many oranges are in each basket?",
  },
  {
    id: 179,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีตุ๊กตา 48 ตัว แบ่งใส่กล่องกล่องละ 6 ตัว จะได้กี่กล่อง",
    en: "There are 48 dolls. If 6 dolls are put into each box, how many boxes are there?",
  },
  {
    id: 180,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีขนม 75 ชิ้น แบ่งใส่ถุง 5 ถุงเท่า ๆ กัน ถุงละกี่ชิ้น",
    en: "There are 75 snacks. They are shared equally among 5 bags. How many snacks are in each bag?",
  },
  {
    id: 181,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีดินสอ 81 แท่ง แบ่งให้เด็ก 9 คนเท่า ๆ กัน เด็กคนละกี่แท่ง",
    en: "There are 81 pencils. They are shared equally among 9 children. How many pencils does each child get?",
  },
  {
    id: 182,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีลูกอม 84 เม็ด แบ่งใส่ถุงถุงละ 7 เม็ด จะได้กี่ถุง",
    en: "There are 84 candies. If 7 candies are put into each bag, how many bags are there?",
  },
  {
    id: 183,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีผลไม้ 60 ลูก แบ่งให้เด็ก 12 คนเท่า ๆ กัน เด็กคนละกี่ลูก",
    en: "There are 60 fruits. They are shared equally among 12 children. How many fruits does each child get?",
  },
  {
    id: 184,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีปลานิล 72 ตัว แบ่งใส่บ่อ 8 บ่อเท่า ๆ กัน บ่อละกี่ตัว",
    en: "There are 72 tilapia fish. They are divided equally into 8 ponds. How many fish are in each pond?",
  },
  {
    id: 185,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีหนังสือนิทาน 96 เล่ม แบ่งให้ห้องเรียน 6 ห้องเท่า ๆ กัน ห้องละกี่เล่ม",
    en: "There are 96 storybooks. They are shared equally among 6 classrooms. How many books does each classroom get?",
  },
  {
    id: 186,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีขนมปัง 64 ชิ้น แบ่งใส่ถาด 8 ถาดเท่า ๆ กัน ถาดละกี่ชิ้น",
    en: "There are 64 pieces of bread. They are divided equally onto 8 trays. How many pieces are on each tray?",
  },
  {
    id: 187,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีดอกกุหลาบ 56 ดอก แบ่งจัดใส่แจกัน 7 ใบเท่า ๆ กัน แจกันละกี่ดอก",
    en: "There are 56 roses. They are divided equally into 7 vases. How many roses are in each vase?",
  },
  {
    id: 188,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีน้ำส้ม 108 ขวด แบ่งใส่ลังลังละ 12 ขวด จะได้กี่ลัง",
    en: "There are 108 bottles of orange juice. If each crate holds 12 bottles, how many crates are there?",
  },
  {
    id: 189,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีลูกโป่ง 48 ใบ แบ่งให้เด็ก 6 คนเท่า ๆ กัน เด็กคนละกี่ใบ",
    en: "There are 48 balloons. They are shared equally among 6 children. How many balloons does each child get?",
  },
  {
    id: 190,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีชอล์ก 100 แท่ง แบ่งใส่กล่องกล่องละ 10 แท่ง จะได้กี่กล่อง",
    en: "There are 100 pieces of chalk. If 10 pieces are put into each box, how many boxes are there?",
  },
  {
    id: 191,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีขวดน้ำ 72 ขวด แบ่งใส่ลัง 9 ลังเท่า ๆ กัน ลังละกี่ขวด",
    en: "There are 72 bottles of water. They are divided equally into 9 crates. How many bottles are in each crate?",
  },
  {
    id: 192,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีลูกแก้ว 63 ลูก แบ่งให้เด็ก 7 คนเท่า ๆ กัน เด็กคนละกี่ลูก",
    en: "There are 63 marbles. They are shared equally among 7 children. How many marbles does each child get?",
  },
  {
    id: 193,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีสมุด 84 เล่ม แบ่งใส่กล่องกล่องละ 12 เล่ม จะได้กี่กล่อง",
    en: "There are 84 notebooks. If 12 notebooks are put into each box, how many boxes are there?",
  },
  {
    id: 194,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีส้ม 96 ลูก แบ่งใส่ถุง 8 ถุงเท่า ๆ กัน ถุงละกี่ลูก",
    en: "There are 96 oranges. They are divided equally into 8 bags. How many oranges are in each bag?",
  },
  {
    id: 195,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีขนม 90 ชิ้น แบ่งให้เด็ก 10 คนเท่า ๆ กัน เด็กคนละกี่ชิ้น",
    en: "There are 90 snacks. They are shared equally among 10 children. How many snacks does each child get?",
  },
  {
    id: 196,
    topic: "การหาร",
    topicEN: "Division",
    th: "มีดินสอสี 120 แท่ง แบ่งใส่กล่องกล่องละ 15 แท่ง จะได้กี่กล่อง",
    en: "There are 120 colored pencils. If 15 pencils are put into each box, how many boxes are there?",
  },

  // ===== เรื่อง โจทย์ปัญหาบวกลบคูณหารระคน (All Operations Mixed) =====
  {
    id: 197,
    topic: "บวกลบคูณหารระคน",
    topicEN: "All Operations Mixed",
    th: "แม่มีขนม 4 ถุง ถุงละ 6 ชิ้น แม่แจกให้เด็ก ๆ ไป 9 ชิ้น แล้วนำขนมที่เหลือไปแบ่งให้เด็ก 3 คนเท่า ๆ กัน เด็กแต่ละคนจะได้ขนมกี่ชิ้น",
    en: "Mother has 4 bags of snacks. Each bag has 6 snacks. She gives 9 snacks to the children. Then she shares the remaining snacks equally among 3 children. How many snacks does each child get?",
  },
  {
    id: 198,
    topic: "บวกลบคูณหารระคน",
    topicEN: "All Operations Mixed",
    th: "โรงเรียนมีดินสอ 5 กล่อง กล่องละ 10 แท่ง ครูแจกให้นักเรียนไป 18 แท่ง แล้วนำดินสอที่เหลือมาแบ่งใส่ถาด 4 ถาดเท่า ๆ กัน แต่ละถาดจะมีดินสอกี่แท่ง",
    en: "A school has 5 boxes of pencils. Each box has 10 pencils. The teacher gives out 18 pencils to students. Then she shares the remaining pencils equally into 4 trays. How many pencils are in each tray?",
  },
];

// Helper: get all unique topics
export const topics = [...new Set(questions.map((q) => q.topic))];

// Helper: filter by topic
export const getByTopic = (topic) =>
  questions.filter((q) => q.topic === topic);

// Helper: get a random question
export const getRandomQuestion = () =>
  questions[Math.floor(Math.random() * questions.length)];

// Helper: get a random question by topic
export const getRandomByTopic = (topic) => {
  const filtered = getByTopic(topic);
  return filtered[Math.floor(Math.random() * filtered.length)];
};

export default questions;
